services:
  zookeeper:
    container_name: zookeeper
    image: buettner123/zookeeper
    build:
      args:
        - kafka_version=$KAFKA_VERSION
        - scala_version=$SCALA_VERSION
        - kafka_home=$KAFKA_HOME
      context: ./zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_HOME=$KAFKA_HOME
    volumes:
      - ./config/zookeeper.properties:$KAFKA_HOME/config/zookeeper.properties
      - /tmp/zookeeper/:/tmp/zookeeper/
    networks:
      - kafka
  broker-1:
    extends:
      file: broker-base.yml
      service: broker
    volumes:
      - ./config/broker-1.properties:$KAFKA_HOME/config/server.properties
      - /tmp/kafka-1/:/tmp/kafka-logs/
  broker-2:
    extends:
      file: broker-base.yml
      service: broker
    volumes:
      - ./config/broker-2.properties:$KAFKA_HOME/config/server.properties
      - /tmp/kafka-2/:/tmp/kafka-logs/
  broker-3:
    extends:
      file: broker-base.yml
      service: broker
    volumes:
      - ./config/broker-3.properties:$KAFKA_HOME/config/server.properties
      - /tmp/kafka-3/:/tmp/kafka-logs/

networks:
  kafka:
    name: kafka
